services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
    - POSTGRES_USER=root
    - POSTGRES_DB=root
    - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "9999:5432"
